added new file

diff --git a/.github/workflows/func-success4.yaml b/.github/workflows/func-success4.yaml
--- a/.github/workflows/func-success4.yaml
+++ b/.github/workflows/func-success4.yaml
@@ -20,6 +20,21 @@ jobs:
   test_success2:
     runs-on: ubuntu-latest
     steps:
+      - name: Step A
+        continue-on-error: true
+        run: exit 1 
+
+      - name: Step B (Skipped)
+        if: false
+        run: echo "Should not run"
+
+      - name: Step C (Runs if all previous steps succeeded)
+        if: success()
+        run: echo "C will run" # <-- Now this runs since we used continue-on error with true!
+
+  test_success3:
+    runs-on: ubuntu-latest
+    steps:
 
       - name: Step A
         run: echo "A passed"
@@ -33,17 +48,4 @@ jobs:
         run: echo "C will run"  
       # <-- Now this success because it skips if previous step is skipped and it consider before that step (step1)!
 
-  test_success3:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Step A
-        continue-on-error: true
-        run: exit 1 
-
-      - name: Step B (Skipped)
-        if: false
-        run: echo "Should not run"
-
-      - name: Step C (Runs if all previous steps succeeded)
-        if: success()
-        run: echo "C will run" # <-- Now this fails!
+  
