added new file

diff --git a/.github/workflows/func-success4.yaml b/.github/workflows/func-success4.yaml
--- a/.github/workflows/func-success4.yaml
+++ b/.github/workflows/func-success4.yaml
@@ -33,3 +33,17 @@ jobs:
         run: echo "C will run"  
       # <-- Now this success because it skips if previous step is skipped and it consider before that step (step1)!
 
+  test_success3:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Step A
+        run: exit 1 
+        continue_on_error: true
+
+      - name: Step B (Skipped)
+        if: false
+        run: echo "Should not run"
+
+      - name: Step C (Runs if all previous steps succeeded)
+        if: success()
+        run: echo "C will run" # <-- Now this fails!
